version: '3.7'

services:
  db:
    image: postgres:16.4-alpine
    platform: linux/x86_64 # it is required to work on apple silicon
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '1'
          memory: 4G
    ports:
      - "5433:5432"
    networks:
      - network
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
      - ./dumps/:/tmp/dumps

  web:
    platform: linux/x86_64 # it is required to work on apple silicon
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 3 && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000" # django test server port
    networks:
      - network
    depends_on:
      - db

networks:
  network: