# Generated by Django 5.1.2 on 2024-10-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("brightmls", "0001_initial"),
        ("brightmls", "0002_alter_city_cty_city_towhnship"),
        ("brightmls", "0003_alter_city_options_and_more"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "cty_city_key",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("cty_city_name", models.CharField(max_length=50, null=True)),
                ("cty_city_county", models.CharField(max_length=255, null=True)),
                ("cty_city_type", models.CharField(max_length=255, null=True)),
                ("cty_city_towhnship", models.IntegerField(null=True)),
                ("cty_county_state", models.CharField(max_length=255, null=True)),
                ("cty_modification_timestamp", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
                "ordering": ["cty_city_key"],
                "verbose_name_plural": "Cities",
                "indexes": [
                    models.Index(
                        fields=["cty_city_name"], name="brightmls_c_cty_cit_6a1de2_idx"
                    ),
                    models.Index(
                        fields=["cty_city_county"],
                        name="brightmls_c_cty_cit_1ba670_idx",
                    ),
                    models.Index(
                        fields=["cty_city_type"], name="brightmls_c_cty_cit_e7cc8f_idx"
                    ),
                    models.Index(
                        fields=["cty_county_state"],
                        name="brightmls_c_cty_cou_0e645e_idx",
                    ),
                ],
            },
        ),
    ]
