# Generated by Django 5.1.2 on 2024-10-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0002_alter_sysofficemedia_sysmediadisplayorder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyArea",
            fields=[
                ("Location", models.CharField(max_length=255, null=True)),
                (
                    "PropAreaKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("PropAreaCounty", models.CharField(max_length=255, null=True)),
                ("PropAreaType", models.CharField(max_length=255, null=True)),
                (
                    "PropAreaModificationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
                ("PropAreaState", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
