# Generated by Django 5.1.2 on 2024-10-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("brightmls", "0004_lookup"),
        ("brightmls", "0005_alter_lookup_options_and_more"),
    ]

    dependencies = [
        ("brightmls", "0003_alter_city_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lookup",
            fields=[
                (
                    "lookup_key",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("lookup_name", models.CharField(max_length=64, null=True)),
                ("lookup_value", models.CharField(max_length=1024, null=True)),
                ("standard_lookup_value", models.CharField(max_length=1024, null=True)),
                ("legacy_odata_value", models.CharField(max_length=20, null=True)),
                ("modification_timestamp", models.DateTimeField(null=True)),
            ],
            options={
                "ordering": ["lookup_name", "lookup_value"],
                "indexes": [
                    models.Index(
                        fields=["lookup_key"], name="brightmls_l_lookup__ab9494_idx"
                    ),
                    models.Index(
                        fields=["lookup_name"], name="brightmls_l_lookup__319939_idx"
                    ),
                    models.Index(
                        fields=["lookup_value"], name="brightmls_l_lookup__7c2082_idx"
                    ),
                    models.Index(
                        fields=["lookup_name", "lookup_value"],
                        name="brightmls_l_lookup__802ef5_idx",
                    ),
                ],
            },
        ),
    ]
