# Generated by Django 5.1.2 on 2024-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0003_propertyarea"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedLookup",
            fields=[
                ("LookupKey", models.BigIntegerField(null=True)),
                (
                    "RelatedLookupKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("ModificationTimestamp", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
