# Generated by Django 5.1.2 on 2024-10-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0004_relatedlookup"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityZipCode",
            fields=[
                (
                    "CityZipCodeKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("CityZipCodeCity", models.CharField(max_length=255, null=True)),
                ("CityZipCodeCityName", models.CharField(max_length=50, null=True)),
                ("CityZipCodeCounty", models.CharField(max_length=255, null=True)),
                ("CityZipCodeState", models.CharField(max_length=255, null=True)),
                ("CityZipCodeZip", models.CharField(max_length=5, null=True)),
                ("CityZipCodePreferredCity", models.BooleanField(null=True)),
                (
                    "CityZipModificationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
            ],
        ),
    ]
