# Generated by Django 5.1.2 on 2024-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("brightmls", "0006_brightmedia"),
        ("brightmls", "0007_alter_brightmedia_listingsourcerecordkey"),
        ("brightmls", "0008_alter_brightmedia_mediaurl_and_more"),
    ]

    dependencies = [
        ("brightmls", "0005_cityzipcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrightMedia",
            fields=[
                ("Location", models.CharField(max_length=255, null=True)),
                ("PropertyType", models.CharField(max_length=255, null=True)),
                ("County", models.CharField(max_length=255, null=True)),
                ("MediaBytes", models.CharField(max_length=255, null=True)),
                ("MediaCategory", models.CharField(max_length=255, null=True)),
                ("MediaCreationTimestamp", models.CharField(max_length=255, null=True)),
                ("MediaExternalKey", models.BigIntegerField(null=True)),
                ("MediaFileName", models.CharField(max_length=3000, null=True)),
                ("MediaImageOf", models.CharField(max_length=255, null=True)),
                ("MediaItemNumber", models.BigIntegerField(null=True)),
                ("MediaKey", models.BigIntegerField(primary_key=True, serialize=False)),
                ("MediaLongDescription", models.CharField(max_length=1024, null=True)),
                (
                    "MediaModificationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
                ("MediaDisplayOrder", models.BigIntegerField(null=True)),
                ("MediaOriginalBytes", models.CharField(max_length=255, null=True)),
                ("MediaOriginalHeight", models.BigIntegerField(null=True)),
                ("MediaOriginalWidth", models.BigIntegerField(null=True)),
                ("MediaShortDescription", models.CharField(max_length=50, null=True)),
                ("MediaSizeDescription", models.CharField(max_length=255, null=True)),
                ("MediaSourceFileName", models.CharField(max_length=3000, null=True)),
                ("MediaSubSystemLocale", models.CharField(max_length=255, null=True)),
                ("MediaSystemLocale", models.CharField(max_length=255, null=True)),
                ("MediaType", models.CharField(max_length=255, null=True)),
                ("MediaURL", models.URLField(max_length=8000, null=True)),
                ("MediaURLFull", models.URLField(max_length=4000, null=True)),
                ("MediaURLHD", models.URLField(max_length=4000, null=True)),
                ("MediaURLHiRes", models.URLField(max_length=4000, null=True)),
                ("MediaURLMedium", models.URLField(max_length=4000, null=True)),
                ("MediaURLThumb", models.URLField(max_length=4000, null=True)),
                ("MlsStatus", models.CharField(max_length=255, null=True)),
                ("PreferredPhotoYN", models.BooleanField(null=True)),
                ("ResourceName", models.CharField(max_length=255, null=True)),
                ("ListingId", models.CharField(max_length=255, null=True)),
                ("ResourceRecordKey", models.BigIntegerField(null=True)),
                ("MediaVendorID", models.CharField(max_length=30, null=True)),
                ("MediaVendorName", models.CharField(max_length=80, null=True)),
                ("MediaVendorIDType", models.CharField(max_length=255, null=True)),
                (
                    "MediaSourceBusinessPartner",
                    models.CharField(max_length=255, null=True),
                ),
                ("MediaSourceInput", models.CharField(max_length=255, null=True)),
                ("MediaSourceTransport", models.CharField(max_length=255, null=True)),
                ("MediaImageHeight", models.BigIntegerField(null=True)),
                ("MediaImageWidth", models.BigIntegerField(null=True)),
                ("ListingSourceRecordKey", models.CharField(max_length=255, null=True)),
                ("MediaVisibility", models.CharField(max_length=255, null=True)),
                (
                    "PropMediaProcessingStatus",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "PropMediaPendingFileName",
                    models.CharField(max_length=3000, null=True),
                ),
                (
                    "PropMediaExtSysProcessingCode",
                    models.CharField(max_length=4000, null=True),
                ),
                ("PropMediaExtSysProcessingTime", models.BigIntegerField(null=True)),
                ("PropMediaExtSysResizeTime", models.BigIntegerField(null=True)),
                (
                    "PropMediaExtSysTotalBytes",
                    models.CharField(max_length=255, null=True),
                ),
                ("PropMediaExtSysWriteTime", models.BigIntegerField(null=True)),
                (
                    "PropMediaExtSysErrorMessage",
                    models.CharField(max_length=4000, null=True),
                ),
                ("MediaObjectId", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
