# Generated by Django 5.1.2 on 2024-10-28 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("brightmls", "0006_relatedlookup"),
        ("brightmls", "0007_alter_relatedlookup_related_lookup_key"),
    ]

    dependencies = [
        ("brightmls", "0005_alter_lookup_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_lookup_key",
                    models.BigIntegerField(
                        help_text="I do not know what this field is, it is not unique and not a foreign key of any Lookup. It is not used in RESO 1.7 too"
                    ),
                ),
                ("modification_timestamp", models.DateTimeField(null=True)),
                (
                    "lookup_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brightmls.lookup",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["related_lookup_key"],
                        name="brightmls_r_related_9327bf_idx",
                    ),
                    models.Index(
                        fields=["lookup_key"], name="brightmls_r_lookup__946693_idx"
                    ),
                ],
            },
        ),
    ]
