# Generated by Django 5.1.2 on 2024-10-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "brightmls",
            "0006_relatedlookup_squashed_0007_alter_relatedlookup_related_lookup_key",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CityZipCode",
            fields=[
                (
                    "city_zip_code_key",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("city_zip_code_city_name", models.CharField(max_length=50, null=True)),
                ("city_zip_code_county", models.CharField(max_length=255, null=True)),
                ("city_zip_code_state", models.CharField(max_length=255, null=True)),
                ("city_zip_code_zip", models.CharField(max_length=5, null=True)),
                ("city_zip_code_preferred_city", models.BooleanField(null=True)),
                ("city_zip_modification_timestamp", models.DateTimeField(null=True)),
                (
                    "city_zip_code_city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="brightmls.city",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "City Zip Codes",
                "ordering": ["city_zip_code_key"],
                "indexes": [
                    models.Index(
                        fields=["city_zip_code_city_name"],
                        name="brightmls_c_city_zi_7dff5f_idx",
                    ),
                    models.Index(
                        fields=["city_zip_code_county"],
                        name="brightmls_c_city_zi_46857e_idx",
                    ),
                    models.Index(
                        fields=["city_zip_code_state"],
                        name="brightmls_c_city_zi_a7245f_idx",
                    ),
                    models.Index(
                        fields=["city_zip_code_zip"],
                        name="brightmls_c_city_zi_8a1c88_idx",
                    ),
                ],
            },
        ),
    ]
