# Generated by Django 5.1.2 on 2024-10-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0009_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deletion",
            fields=[
                ("TableName", models.CharField(max_length=30, null=True)),
                ("SchemaShortName", models.CharField(max_length=5, null=True)),
                (
                    "UniversalKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("DeletionTimestamp", models.CharField(max_length=255, null=True)),
                ("DeleteKey", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
