# Generated by Django 5.1.2 on 2024-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("brightmls", "0012_schooldistrict"),
        ("brightmls", "0013_alter_schooldistrict_schooldistricturl"),
    ]

    dependencies = [
        ("brightmls", "0011_brightoffices"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolDistrict",
            fields=[
                (
                    "SchoolDistrictKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("SchoolDistrictName", models.CharField(max_length=80, null=True)),
                ("SchoolDistrictURL", models.URLField(max_length=4000, null=True)),
                ("SchoolDistrictCounty", models.CharField(max_length=255, null=True)),
                ("SchoolDistrictState", models.CharField(max_length=255, null=True)),
                (
                    "SchoolDistrictModificationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
            ],
        ),
    ]
