# Generated by Django 5.1.2 on 2024-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "brightmls",
            "0012_schooldistrict_squashed_0013_alter_schooldistrict_schooldistricturl",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyPermissions",
            fields=[
                (
                    "PartyPermKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "PartyPermAccessLevelType",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "PartyPermPermissionType",
                    models.CharField(max_length=255, null=True),
                ),
                ("PartyPermGrantorPartyKey", models.BigIntegerField(null=True)),
                ("PartyPermGranteePartyKey", models.BigIntegerField(null=True)),
                ("PartyPermSystemLocale", models.CharField(max_length=255, null=True)),
                ("PpPermissionGroup", models.CharField(max_length=255, null=True)),
                (
                    "PartyPermSubSystemLocale",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "PartyPermModificationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
            ],
        ),
    ]
