# Generated by Django 5.1.2 on 2024-10-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0014_partypermissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brightoffices",
            name="OfficeSourceRecordKey",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
