# Generated by Django 5.1.2 on 2024-10-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("brightmls", "0017_brightopenhouses"),
        ("brightmls", "0018_alter_brightopenhouses_listingsourcerecordkey"),
    ]

    dependencies = [
        ("brightmls", "0016_syspartylicense"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrightOpenHouses",
            fields=[
                ("County", models.CharField(max_length=255, null=True)),
                ("ListingId", models.CharField(max_length=255, null=True)),
                ("MlsStatus", models.CharField(max_length=255, null=True)),
                ("OpenHouseAttendedBy", models.CharField(max_length=255, null=True)),
                (
                    "OpenHouseCreationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
                ("OpenHouseDate", models.CharField(max_length=255, null=True)),
                ("OpenHouseItemNumber", models.BigIntegerField(null=True)),
                ("OpenHouseEndTime", models.CharField(max_length=255, null=True)),
                (
                    "OpenHouseKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("OpenHouseListingKey", models.BigIntegerField(null=True)),
                (
                    "OpenHouseModificationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "OpenHouseSourceBusinessPartner",
                    models.CharField(max_length=255, null=True),
                ),
                ("OpenHouseSourceInput", models.CharField(max_length=255, null=True)),
                ("OpenHouseRemarks", models.CharField(max_length=500, null=True)),
                (
                    "OpenHouseSourceTransport",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "OpenHouseSubSystemLocale",
                    models.CharField(max_length=255, null=True),
                ),
                ("OpenHouseSystemLocale", models.CharField(max_length=255, null=True)),
                ("ListingSourceRecordKey", models.CharField(max_length=255, null=True)),
                (
                    "OpenHouseExternalSystemID",
                    models.CharField(max_length=30, null=True),
                ),
                ("ListOfficeMlsId", models.CharField(max_length=25, null=True)),
                ("OpenHouseStartTime", models.CharField(max_length=255, null=True)),
                ("OpenHouseType", models.CharField(max_length=255, null=True)),
                ("OpenHouseMethod", models.CharField(max_length=255, null=True)),
                ("VirtualOpenHouseUrl", models.CharField(max_length=4000, null=True)),
                ("ExpectedOnMarketDate", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
