# Generated by Django 5.1.2 on 2024-10-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0018_alter_brightopenhouses_listingsourcerecordkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "PropHistKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("PropHistListingKey", models.BigIntegerField(null=True)),
                ("PropHistRecordKey", models.BigIntegerField(null=True)),
                ("PropHistPartyKey", models.BigIntegerField(null=True)),
                ("PropHistChangeType", models.CharField(max_length=20, null=True)),
                ("PropHistChangeTypeLkp", models.CharField(max_length=255, null=True)),
                (
                    "PropHistChangeTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
                ("PropHistColumnName", models.CharField(max_length=64, null=True)),
                ("PropHistTableName", models.CharField(max_length=30, null=True)),
                (
                    "PropHistOriginalColumnValue",
                    models.CharField(max_length=4000, null=True),
                ),
                (
                    "PropHistNewColumnValue",
                    models.CharField(max_length=4000, null=True),
                ),
                (
                    "PropHistOriginalPickListValue",
                    models.CharField(max_length=4000, null=True),
                ),
                (
                    "PropHistNewPickListValue",
                    models.CharField(max_length=4000, null=True),
                ),
                ("PropHistItemNumber", models.BigIntegerField(null=True)),
                (
                    "PropHistSubSystemLocale",
                    models.CharField(max_length=255, null=True),
                ),
                ("PropHistSystemLocale", models.CharField(max_length=255, null=True)),
                ("ListingID", models.CharField(max_length=20, null=True)),
                ("FullStreetAddress", models.CharField(max_length=80, null=True)),
                ("SystemName", models.CharField(max_length=50, null=True)),
                ("BasicComingSoonEndDate", models.CharField(max_length=255, null=True)),
                (
                    "BasicLocaleListingStatus",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "PropHistNewColumnCharValue",
                    models.CharField(max_length=4000, null=True),
                ),
                (
                    "PropHistNewColumnDatetimeValue",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "PropHistNewColumnNumValue",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "PropHistOriginalColumnCharValue",
                    models.CharField(max_length=4000, null=True),
                ),
                (
                    "PropHistOriginalColumnDatetimeValue",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "PropHistOriginalColumnNumValue",
                    models.CharField(max_length=255, null=True),
                ),
                ("PropHistHistColumnKey", models.BigIntegerField(null=True)),
            ],
        ),
    ]
