# Generated by Django 5.1.2 on 2024-10-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("brightmls", "0020_greenverification"),
        ("brightmls", "0021_alter_greenverification_listingsourcerecordkey"),
    ]

    dependencies = [
        ("brightmls", "0019_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="GreenVerification",
            fields=[
                (
                    "GreenVerificationKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "GreenVerificationSystemLocale",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "GreenVerificationSubSystemLocale",
                    models.CharField(max_length=255, null=True),
                ),
                ("GreenVerificationListingKey", models.BigIntegerField(null=True)),
                ("GreenVerificationBody", models.CharField(max_length=255, null=True)),
                (
                    "GreenVerificationProgramType",
                    models.CharField(max_length=255, null=True),
                ),
                ("GreenVerificationYear", models.BigIntegerField(null=True)),
                (
                    "GreenVerificationRating",
                    models.CharField(max_length=255, null=True),
                ),
                ("GreenVerificationScore", models.BigIntegerField(null=True)),
                (
                    "GreenVerificationStatus",
                    models.CharField(max_length=255, null=True),
                ),
                ("County", models.CharField(max_length=255, null=True)),
                ("ListingSourceRecordKey", models.CharField(max_length=255, null=True)),
                (
                    "GreenVerificationModificationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
            ],
        ),
    ]
