# Generated by Django 5.1.2 on 2024-10-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0021_alter_greenverification_listingsourcerecordkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "CtyCityKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("CtyCityName", models.CharField(max_length=50, null=True)),
                ("CtyCityCounty", models.CharField(max_length=255, null=True)),
                ("CtyCityType", models.CharField(max_length=255, null=True)),
                ("CtyCityTowhnship", models.CharField(max_length=255, null=True)),
                ("CtyCountyState", models.CharField(max_length=255, null=True)),
                (
                    "CtyModificationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
            ],
        ),
    ]
