# Generated by Django 5.1.2 on 2024-10-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("brightmls", "0023_brightmembers"),
        ("brightmls", "0024_alter_brightmembers_membersourcerecordkey"),
    ]

    dependencies = [
        ("brightmls", "0022_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrightMembers",
            fields=[
                ("JobTitle", models.CharField(max_length=50, null=True)),
                ("MemberAddress1", models.CharField(max_length=50, null=True)),
                ("MemberAddress2", models.CharField(max_length=50, null=True)),
                ("MemberBoxNumber", models.CharField(max_length=10, null=True)),
                ("MemberCity", models.CharField(max_length=50, null=True)),
                ("MemberCountry", models.CharField(max_length=255, null=True)),
                ("MemberCounty", models.CharField(max_length=255, null=True)),
                ("MemberDesignation", models.CharField(max_length=255, null=True)),
                ("MemberDirectPhone", models.CharField(max_length=16, null=True)),
                ("MemberEmail", models.CharField(max_length=80, null=True)),
                ("MemberFax", models.CharField(max_length=16, null=True)),
                ("MemberFirstName", models.CharField(max_length=50, null=True)),
                ("MemberFullName", models.CharField(max_length=150, null=True)),
                ("MemberFullRoleList", models.CharField(max_length=4000, null=True)),
                ("MemberJoinDate", models.CharField(max_length=255, null=True)),
                (
                    "MemberKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("MemberLastName", models.CharField(max_length=50, null=True)),
                (
                    "MemberLicenseExpirationDate",
                    models.CharField(max_length=255, null=True),
                ),
                ("MemberLoginId", models.CharField(max_length=25, null=True)),
                ("MemberMiddleInitial", models.CharField(max_length=5, null=True)),
                ("MemberMiddleName", models.CharField(max_length=50, null=True)),
                ("MemberMlsId", models.CharField(max_length=25, null=True)),
                ("MemberMobilePhone", models.CharField(max_length=16, null=True)),
                ("MemberNamePrefix", models.CharField(max_length=255, null=True)),
                ("MemberNameSuffix", models.CharField(max_length=255, null=True)),
                (
                    "MemberNationalAssociationId",
                    models.CharField(max_length=25, null=True),
                ),
                ("MemberNickname", models.CharField(max_length=50, null=True)),
                ("MemberNumViolations", models.BigIntegerField(null=True)),
                ("MemberOfficePhone", models.CharField(max_length=16, null=True)),
                ("MemberOfficePhoneExt", models.BigIntegerField(null=True)),
                ("MemberPager", models.CharField(max_length=16, null=True)),
                ("MemberPostalCode", models.CharField(max_length=10, null=True)),
                ("MemberPostalCodePlus4", models.CharField(max_length=4, null=True)),
                ("MemberPreferredPhone", models.CharField(max_length=16, null=True)),
                ("MemberPreferredPhoneExt", models.BigIntegerField(null=True)),
                ("MemberPrivateEmail", models.CharField(max_length=3000, null=True)),
                ("MemberRatePlugFlag", models.BooleanField(null=True)),
                (
                    "MemberReinstatementDate",
                    models.CharField(max_length=255, null=True),
                ),
                ("MemberRoleList", models.CharField(max_length=4000, null=True)),
                ("MemberStateLicense", models.CharField(max_length=50, null=True)),
                (
                    "MemberStateLicenseState",
                    models.CharField(max_length=255, null=True),
                ),
                ("MemberStateOrProvince", models.CharField(max_length=255, null=True)),
                ("MemberStatus", models.CharField(max_length=255, null=True)),
                ("MemberStreetDirSuffix", models.CharField(max_length=255, null=True)),
                ("MemberStreetException", models.CharField(max_length=10, null=True)),
                ("MemberStreetName", models.CharField(max_length=50, null=True)),
                ("MemberStreetNumber", models.BigIntegerField(null=True)),
                ("MemberStreetSuffix", models.CharField(max_length=255, null=True)),
                ("MemberTerminationDate", models.CharField(max_length=255, null=True)),
                ("MemberType", models.CharField(max_length=255, null=True)),
                ("MemberSubType", models.CharField(max_length=255, null=True)),
                ("MemberUnitDesignation", models.CharField(max_length=255, null=True)),
                ("MemberUnitNumber", models.CharField(max_length=20, null=True)),
                ("MemberVoiceMailExt", models.CharField(max_length=15, null=True)),
                ("MemberVoiceMail", models.CharField(max_length=16, null=True)),
                ("ModificationTimestamp", models.CharField(max_length=255, null=True)),
                ("OfficeKey", models.BigIntegerField(null=True)),
                ("OfficeMlsId", models.CharField(max_length=25, null=True)),
                ("OfficeBrokerKey", models.BigIntegerField(null=True)),
                ("OfficeName", models.CharField(max_length=80, null=True)),
                ("OfficeBrokerMlsId", models.CharField(max_length=25, null=True)),
                ("MemberDateAdded", models.CharField(max_length=255, null=True)),
                (
                    "SocialMediaBlogUrlOrId",
                    models.CharField(max_length=8000, null=True),
                ),
                (
                    "SocialMediaFacebookUrlOrId",
                    models.CharField(max_length=8000, null=True),
                ),
                (
                    "SocialMediaLinkedInUrlOrId",
                    models.CharField(max_length=8000, null=True),
                ),
                (
                    "SocialMediaTwitterUrlOrId",
                    models.CharField(max_length=8000, null=True),
                ),
                (
                    "SocialMediaWebsiteUrlOrId",
                    models.CharField(max_length=8000, null=True),
                ),
                (
                    "SocialMediaYouTubeUrlOrId",
                    models.CharField(max_length=8000, null=True),
                ),
                ("MemberSourceInput", models.CharField(max_length=255, null=True)),
                ("MemberSourceRecordKey", models.CharField(max_length=255, null=True)),
                ("MemberSourceRecordID", models.CharField(max_length=128, null=True)),
                (
                    "MemberSourceBusinessPartner",
                    models.CharField(max_length=255, null=True),
                ),
                ("MemberSourceTransport", models.CharField(max_length=255, null=True)),
                ("SyndicateTo", models.CharField(max_length=255, null=True)),
                ("MemberSubSystemLocale", models.CharField(max_length=255, null=True)),
                ("MemberSystemLocale", models.CharField(max_length=255, null=True)),
                (
                    "MemberPreferredFirstName",
                    models.CharField(max_length=128, null=True),
                ),
                (
                    "MemberPreferredLastName",
                    models.CharField(max_length=128, null=True),
                ),
                ("MemberBrightConvertedYN", models.BooleanField(null=True)),
                (
                    "MemberAssociationPrimary",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "MemberAssociationsFullList",
                    models.CharField(max_length=255, null=True),
                ),
                ("MemberPreviewYN", models.BooleanField(null=True)),
                (
                    "SourceModificationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
                ("MemberStreetDirPrefix", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
