# Generated by Django 5.1.2 on 2024-10-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("brightmls", "0025_unit"),
        ("brightmls", "0026_alter_unit_listingsourcerecordkey"),
    ]

    dependencies = [
        (
            "brightmls",
            "0023_brightmembers_squashed_0024_alter_brightmembers_membersourcerecordkey",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("County", models.CharField(max_length=255, null=True)),
                (
                    "UnitTypeKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("UnitTypeListingKey", models.BigIntegerField(null=True)),
                ("UnitTypeItemNumber", models.BigIntegerField(null=True)),
                ("UnitTypeType", models.CharField(max_length=255, null=True)),
                ("UnitTypeMonthlyRent", models.CharField(max_length=255, null=True)),
                ("UnitTypeProForma", models.CharField(max_length=255, null=True)),
                ("UnitTypeOccupiedYN", models.BooleanField(null=True)),
                ("UnitTypeLevel", models.CharField(max_length=255, null=True)),
                ("UnitTypeFinishedSQFT", models.BigIntegerField(null=True)),
                ("UnitTypeLeaseType", models.CharField(max_length=255, null=True)),
                (
                    "UnitTypeLeaseExpirationDate",
                    models.CharField(max_length=255, null=True),
                ),
                ("UnitTypeBedsTotal", models.BigIntegerField(null=True)),
                ("UnitTypeBathsHalf", models.CharField(max_length=255, null=True)),
                ("UnitTypeBathsFull", models.BigIntegerField(null=True)),
                ("UnitTypeBathsTotal", models.CharField(max_length=255, null=True)),
                ("UnitTypeFeatures", models.CharField(max_length=128, null=True)),
                ("UnitTypeTotalRooms", models.BigIntegerField(null=True)),
                ("UnitTypeContiguousSpaceYN", models.BooleanField(null=True)),
                (
                    "UnitTypeSecurityDeposit",
                    models.CharField(max_length=255, null=True),
                ),
                ("ListingSourceRecordKey", models.CharField(max_length=255, null=True)),
                (
                    "PropUnitModificationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
                ("UnitSystemLocale", models.CharField(max_length=255, null=True)),
                ("UnitSubSystemLocale", models.CharField(max_length=255, null=True)),
                (
                    "UnitTypeSourceRecordKey",
                    models.CharField(max_length=255, null=True),
                ),
            ],
        ),
    ]
