# Generated by Django 5.1.2 on 2024-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0025_unit_squashed_0026_alter_unit_listingsourcerecordkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lookup",
            fields=[
                (
                    "LookupKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("LookupName", models.CharField(max_length=64, null=True)),
                ("LookupValue", models.CharField(max_length=1024, null=True)),
                ("StandardLookupValue", models.CharField(max_length=1024, null=True)),
                ("LegacyODataValue", models.CharField(max_length=20, null=True)),
                ("ModificationTimestamp", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
