# Generated by Django 5.1.2 on 2024-10-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0027_lookup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subdivision",
            fields=[
                (
                    "LoSubdivisionKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("LoSubdivisionName", models.CharField(max_length=50, null=True)),
                ("LoSubdivisionSystemValidatedFlag", models.BooleanField(null=True)),
                ("LoSubdivisionCounty", models.CharField(max_length=255, null=True)),
                ("LoSubdivisionState", models.CharField(max_length=255, null=True)),
                (
                    "LoSubdivisionModificationTimestamp",
                    models.CharField(max_length=255, null=True),
                ),
                ("LoSubdivisionStatus", models.CharField(max_length=255, null=True)),
                ("LoSubdivisionURL", models.URLField(null=True)),
                (
                    "LoSubdivisionRelatedSubdivisionKey",
                    models.BigIntegerField(null=True),
                ),
            ],
        ),
    ]
