# Generated by Django 5.1.2 on 2024-10-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0029_sysagentmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("TeamKey", models.BigIntegerField(primary_key=True, serialize=False)),
                ("TeamName", models.CharField(max_length=80, null=True)),
                ("TeamSystemLocale", models.CharField(max_length=255, null=True)),
                ("TeamSubSystemLocale", models.CharField(max_length=255, null=True)),
                ("TeamLeadMemberKey", models.BigIntegerField(null=True)),
                ("TeamModificationTimestamp", models.DateTimeField(null=True)),
                ("TeamStatus", models.CharField(max_length=255, null=True)),
                ("TeamExternalSystemID", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
