# Generated by Django 5.1.2 on 2024-10-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0030_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("SchoolName", models.CharField(max_length=80, null=True)),
                ("SchoolCounty", models.CharField(max_length=255, null=True)),
                (
                    "SchoolKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("SchoolDistrictName", models.CharField(max_length=80, null=True)),
                ("SchoolDistrictKey", models.BigIntegerField(null=True)),
                ("SchoolModificationTimestamp", models.DateTimeField(null=True)),
                ("SchoolType", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
