# Generated by Django 5.1.2 on 2024-10-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0031_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingName",
            fields=[
                (
                    "BldgNameKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("BldgNameName", models.CharField(max_length=50, null=True)),
                ("BldgNameRelatedBldgNameKey", models.BigIntegerField(null=True)),
                ("BldgNameStatus", models.CharField(max_length=255, null=True)),
                ("BldgNameURL", models.URLField(null=True)),
                ("BldgNameCounty", models.CharField(max_length=255, null=True)),
                ("BldgNameState", models.CharField(max_length=255, null=True)),
                ("BldgNameModificationTimestamp", models.DateTimeField(null=True)),
            ],
        ),
    ]
