# Generated by Django 5.1.2 on 2024-10-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0032_buildingname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("RoomKey", models.BigIntegerField(primary_key=True, serialize=False)),
                ("RoomListingKey", models.BigIntegerField(null=True)),
                ("County", models.CharField(max_length=255, null=True)),
                ("RoomType", models.CharField(max_length=255, null=True)),
                ("RoomLength", models.BigIntegerField(null=True)),
                ("RoomWidth", models.BigIntegerField(null=True)),
                ("RoomLevel", models.CharField(max_length=255, null=True)),
                ("RoomExistsYN", models.BooleanField(null=True)),
                ("RoomDisplayOrder", models.BigIntegerField(null=True)),
                ("RoomItemNumber", models.BigIntegerField(null=True)),
                ("RoomArea", models.BigIntegerField(null=True)),
                ("RoomDimensions", models.CharField(max_length=50, null=True)),
                ("RoomFeatures", models.CharField(max_length=255, null=True)),
                ("RoomSystemLocale", models.CharField(max_length=255, null=True)),
                ("RoomSubSystemLocale", models.CharField(max_length=255, null=True)),
                ("ListingSourceRecordKey", models.BigIntegerField(null=True)),
                ("RoomModificationTimestamp", models.DateTimeField(null=True)),
                ("RoomDescription", models.CharField(max_length=1024, null=True)),
                ("RoomSourceRecordKey", models.BigIntegerField(null=True)),
            ],
        ),
    ]
