# Generated by Django 5.1.2 on 2024-10-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("brightmls", "0034_alter_sysagentmedia_sysmediamodificationtimestamp"),
        ("brightmls", "0035_alter_sysagentmedia_sysmediacreationtimestamp"),
        ("brightmls", "0036_alter_brightmedia_mediacreationtimestamp_and_more"),
    ]

    dependencies = [
        ("brightmls", "0033_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysagentmedia",
            name="SysMediaModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="sysagentmedia",
            name="SysMediaCreationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="brightmedia",
            name="MediaCreationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="brightmedia",
            name="MediaModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="brightmembers",
            name="ModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="brightmembers",
            name="SourceModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="brightoffices",
            name="ModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="brightoffices",
            name="SourceModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="brightopenhouses",
            name="OpenHouseCreationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="brightopenhouses",
            name="OpenHouseModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="CtyModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="cityzipcode",
            name="CityZipModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="deletion",
            name="DeletionTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="greenverification",
            name="GreenVerificationModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="PropHistChangeTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="lookup",
            name="ModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="partypermissions",
            name="PartyPermModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="propertyarea",
            name="PropAreaModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="relatedlookup",
            name="ModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="schooldistrict",
            name="SchoolDistrictModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="subdivision",
            name="LoSubdivisionModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="sysofficemedia",
            name="SysMediaCreationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="sysofficemedia",
            name="SysMediaModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="syspartylicense",
            name="SysPartyLicenseModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="TeamMemberModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="PropUnitModificationTimestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
