# Generated by Django 5.1.2 on 2024-10-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "brightmls",
            "0034_alter_sysagentmedia_sysmediamodificationtimestamp_squashed_0036_alter_brightmedia_mediacreationtimestamp_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BuilderModel",
            fields=[
                (
                    "BuilderModelKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("BuilderModelName", models.CharField(max_length=50, null=True)),
                (
                    "BuilderModelRelatedBuilderModelKey",
                    models.BigIntegerField(null=True),
                ),
                ("BuilderModelStatus", models.CharField(max_length=255, null=True)),
                ("BuilderModelCounty", models.CharField(max_length=255, null=True)),
                ("BuilderModelModificationTimestamp", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessHistoryDeletions",
            fields=[
                (
                    "DelUchHistChangeKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("DelUchHistSystemLocale", models.CharField(max_length=255, null=True)),
                (
                    "DelUchHistSubSystemLocale",
                    models.CharField(max_length=255, null=True),
                ),
                ("DelUchHistDeletedTimestamp", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LisBusinessHistory",
            fields=[
                (
                    "UchPropHistChangeKey",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("UchPropHistListingKey", models.BigIntegerField(null=True)),
                ("UchPropHistPartyKey", models.BigIntegerField(null=True)),
                ("UchPropHistChangeType", models.CharField(max_length=20, null=True)),
                ("UchPropHistChangeTypePckItemKey", models.BigIntegerField(null=True)),
                ("UchPropHistChangeTimestamp", models.DateTimeField(null=True)),
                ("SystemName", models.CharField(max_length=50, null=True)),
                ("PropHistColumnName", models.CharField(max_length=64, null=True)),
                ("TableName", models.CharField(max_length=30, null=True)),
                ("TableSchemaKey", models.BigIntegerField(null=True)),
                (
                    "UchPropHistOriginalColumnValue",
                    models.CharField(max_length=4000, null=True),
                ),
                (
                    "UchPropHistNewColumnValue",
                    models.CharField(max_length=4000, null=True),
                ),
                (
                    "UchPropHistOriginalPickListValue",
                    models.CharField(max_length=80, null=True),
                ),
                (
                    "UchPropHistNewPickListValue",
                    models.CharField(max_length=80, null=True),
                ),
                ("UchPropHistItemNumber", models.BigIntegerField(null=True)),
                (
                    "UchPropHistSubSystemLocale",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "UchPropHistSystemLocale",
                    models.CharField(max_length=255, null=True),
                ),
                ("BasicListingID", models.CharField(max_length=20, null=True)),
                ("FullStreetAddress", models.CharField(max_length=80, null=True)),
                ("UchPropHistCreationTimestamp", models.DateTimeField(null=True)),
                ("UchPropHistModificationTimestamp", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PartyProfileOption",
            fields=[
                ("POName", models.CharField(max_length=50, null=True)),
                ("PPOCharValue", models.CharField(max_length=4000, null=True)),
                ("PPODateValue", models.CharField(max_length=255, null=True)),
                ("PPOKey", models.BigIntegerField(primary_key=True, serialize=False)),
                ("PPONumValue", models.CharField(max_length=255, null=True)),
                ("PPOPartyKey", models.BigIntegerField(null=True)),
                ("PPOPOIKey", models.BigIntegerField(null=True)),
                ("PPOUserCustomizableFlag", models.BooleanField(null=True)),
                ("PPOClobValue", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
