# Generated by Django 5.1.2 on 2024-10-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "brightmls",
            "0038_brightproperties_squashed_0053_alter_brightmedia_propmediaextsysresizetime_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={"ordering": ["-PropHistChangeTimestamp"]},
        ),
        migrations.AddIndex(
            model_name="history",
            index=models.Index(
                fields=["PropHistChangeTimestamp"],
                name="brightmls_h_PropHis_46218c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="history",
            index=models.Index(
                fields=["PropHistListingKey"], name="brightmls_h_PropHis_b2d181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="history",
            index=models.Index(
                fields=["PropHistTableName"], name="brightmls_h_PropHis_3271b4_idx"
            ),
        ),
    ]
