# Generated by Django 5.1.2 on 2024-11-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0054_alter_history_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="history",
            index=models.Index(
                fields=["PropHistChangeType"], name="brightmls_h_PropHis_f2bb3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="history",
            index=models.Index(
                fields=["PropHistColumnName"], name="brightmls_h_PropHis_5933d7_idx"
            ),
        ),
    ]
