# Generated by Django 5.1.2 on 2024-11-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brightmls", "0055_history_brightmls_h_prophis_f2bb3c_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="brightmedia",
            index=models.Index(
                fields=["MediaModificationTimestamp"],
                name="brightmls_b_MediaMo_37c6f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brightmembers",
            index=models.Index(
                fields=["ModificationTimestamp"], name="brightmls_b_Modific_5581b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brightoffices",
            index=models.Index(
                fields=["ModificationTimestamp"], name="brightmls_b_Modific_068886_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brightopenhouses",
            index=models.Index(
                fields=["OpenHouseModificationTimestamp"],
                name="brightmls_b_OpenHou_e2905b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brightproperties",
            index=models.Index(
                fields=["ModificationTimestamp"], name="brightmls_b_Modific_3c3ee6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buildingname",
            index=models.Index(
                fields=["BldgNameModificationTimestamp"],
                name="brightmls_b_BldgNam_676392_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["CtyModificationTimestamp"],
                name="brightmls_c_CtyModi_33eaf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cityzipcode",
            index=models.Index(
                fields=["CityZipModificationTimestamp"],
                name="brightmls_c_CityZip_6c5e0d_idx",
            ),
        ),
    ]
